services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        image: mariadb:42
        restart: always
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mariadb:/var/lib/mysql
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        image: wordpress:42
        restart: always
        depends_on:
            - mariadb
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        image: nginx:42
        restart: always
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
volumes:
    mariadb:
    wordpress:
networks:
    inception: