services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        restart: always
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - mariadb:/var/lib/mysql
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        restart: always
        depends_on:
            - mariadb
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        depends_on:
            - wordpress
        env_file:
            - .env
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /home/mohel-kh/data/mariadb
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/mohel-kh/data/wordpress
            o: bind
networks:
    inception: